AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "config/puma.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 180
