AllCops:
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*.rb"
    - "bin/*"
    - "config/puma.rb"
    - "config/environments/development.rb"
    - "config/environments/production.rb"
    - "spec/spec_helper.rb"
  SuggestExtensions: false
Style/Documentation:
  Enabled: false
Layout/LineLength:
  Max: 180
Metrics/MethodLength:
  Max: 20
Lint/EmptyBlock:
  Enabled: false
Metrics/AbcSize:
  Max: 20
